### ISSUE TITLE
Password refound

### ISSUE THREAD

**Issue by mengyushi** [mengyushi/roommates#13]
User password
House code

**Comment by WangQiuc** [comment]
指望你了

**Comment by mengyushi** [comment]
https://www.railstutorial.org/book/password_reset

**Comment by mengyushi** [comment]
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

**Comment by mengyushi** [comment]
before reset
$2a$10$fy3QT7qP4ui.4xFyKzAj6uEw0iZgq5idddai85GfuktSYWzpxUM2m
--
